site_name: FindGlocal

theme:
  name: material
  language: pt

docs_dir: docs/

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Análise de requisitos:
    - Perfil do usuário: 
      - Questionário: 'requisitos/questionarios.md'
      - Perfil do Usuário: 'requisitos/perfil_do_usuário.md'
      - Personas: 'requisitos/personas.md'
    - Análise de tarefas: 
      - Análise Hierárquica de tarefas: 'requisitos/HTA.md'
      - Árvore de tarefas concorrentes: 'requisitos/CTT.md'
    - Princípios Gerais de Projeto: 'requisitos/principios.md'
    - Metas de Usabilidade: 'requisitos/usabilidade.md'
    - Guia de Estilo: 'requisitos/guiadeestilo.md'
  
  - Design, avaliação e desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: 'Design/nivel1/Tarefas/Planejamento.md'
        - Planejamento do Relato dos Resultados: 'Design/nivel1/Tarefas/Planejamento_relato.md'
        - Relatos:
          - V01: 'Design/nivel1/Tarefas/Piloto_Relato1.md'
          - V02: 'Design/nivel1/Tarefas/Relato2.md'


      - Storyboard:
        - Storyboard:  'Design/nivel1/Storyboard/Storyboard.md'
        - Planejamento da Avaliação: 'Design/nivel1/Storyboard/Planejamento.md'
        - Planejamento do Relato dos Resultados : 'Design/nivel1/Storyboard/Planejamento_relato.md'
        - Relatos:
          - V01: 'Design/nivel1/Storyboard/Piloto_Relato1.md'
          - V02: 'Design/nivel1/Storyboard/Relato2.md'
    
    - Nível 2:
      - Protótipo de baixa fidelidade: 'Design/nivel2/baixa.md'
      - Planejamento da Avaliação: 'Design/nivel2/Planejamento.md'
      - Planejamento do Relato dos Resultados: 'Design/nivel2/Planejamento_relato.md'
      - Relatos:
        - V01: 'Design/nivel2/relato.md'

    - Nível 3: 
      - Protótipo de alta fidelidade: 'Design/nivel3/alta.md'
      - Planejamento da Avaliação: 'Design/nivel3/Planejamento.md'
      - Planejamento do Relato dos Resultados: 'Design/nivel3/Planejamento_relato.md'    
  
  - Análise: 
    - Verificação:
      - Introdução: 'analise/modelo.md'
      - Análise de requisitos:
        - Perfil do usuário: 
          - Questionário: 'analise/requisitos/questionarios.md'
          - Perfil do Usuário: 'analise/requisitos/perfil_do_usuário.md'
          - Personas: 'analise/requisitos/personas.md'
        - Análise de tarefas: 
          - Análise Hierárquica de tarefas: 'analise/requisitos/HTA.md'
          - Árvore de tarefas concorrentes: 'analise/requisitos/CTT.md'
        - Princípios Gerais de Projeto: 'analise/requisitos/principios.md'
        - Metas de Usabilidade: 'analise/requisitos/usabilidade.md'
        - Guia de Estilo: 'analise/requisitos/guiadeestilo.md'
      - Design, avaliação e desenvolvimento:
        - Nível 1:
          - Análise de Tarefas:
            - Planejamento da Avaliação: 'analise/nivel1/Tarefas/Planejamento.md'
            - Planejamento do Relato dos Resultados: 'analise/nivel1/Tarefas/Planejamento_relato.md'
            - Relatos:
              - V01: 'analise/nivel1/Tarefas/Piloto_Relato1.md'
              - V02: 'analise/nivel1/Tarefas/Relato2.md'
          - Storyboard:
            - Storyboard:  'analise/nivel1/Storyboard/Storyboard.md'
            - Planejamento da Avaliação: 'analise/nivel1/Storyboard/Planejamento.md'
            - Planejamento do Relato dos Resultados : 'analise/nivel1/Storyboard/Planejamento_relato.md'
            - Relatos:
              - V01: 'analise/nivel1/Storyboard/Piloto_Relato1.md'
              - V02: 'analise/nivel1/Storyboard/Relato2.md'
        - Nível 2:
          - Protótipo de baixa fidelidade: 'analise/nivel2/baixa.md'
          - Planejamento da Avaliação: 'analise/nivel2/Planejamento.md'
          - Planejamento do Relato dos Resultados: 'analise/nivel2/Planejamento_relato.md'
          - Relatos:
            - V01: 'analise/nivel2/relato.md'
        - Nível 3: 
          - Protótipo de alta fidelidade: 'analise/nivel3/alta.md'
          - Planejamento da Avaliação: 'analise/nivel3/Planejamento.md'
          - Planejamento do Relato dos Resultados: 'analise/nivel3/Planejamento_relato.md'    
      

  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
    - Ata 02: 'Atas/Ata02.md'
    - Ata 03: 'Atas/Ata03.md'
    - Ata 04: 'Atas/Ata04.md'
    - Ata 05: 'Atas/Ata05.md'
    - Ata 06: 'Atas/Ata06.md'
    - Ata 07: 'Atas/Ata07.md'
  
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
    - Apresentação 2: 'Apresentacao/apresentacao2.md'
    - Apresentação 3: 'Apresentacao/apresentacao3.md'
    - Apresentação 4: 'Apresentacao/apresentacao4.md'
    - Apresentação 5: 'Apresentacao/apresentacao5.md'
    - Apresentação 6: 'Apresentacao/apresentacao6.md'
    - Apresentação 7: 'Apresentacao/apresentacao7.md'

