site_name: FindGlocal

theme:
  name: material
  language: pt

docs_dir: docs/

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Análise de requisitos:
    - Perfil do usuário: 
      - Questionário: 'requisitos/questionarios.md'
      - Perfil do Usuário: 'requisitos/perfil_do_usuário.md'
      - Personas: 'requisitos/personas.md'
      - Princípios Gerais de Projeto: 'requisitos/principios.md'
      - Metas de Usabilidade: 'requisitos/usabilidade.md'
      - Guia de Estilo: ''requisitos/guiadeuso.md''
    - Análise de tarefas: 
      - Análise Hierárquica de tarefas: 'requisitos/analise_de_tarefas.md'
  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
    - Ata 02: 'Atas/Ata02.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
    - Apresentação 2: 'Apresentacao/apresentacao2.md'

