site_name: FindGlocal

theme:
  name: material
  language: pt

docs_dir: docs/

nav:
  - Sobre: index.md
  - Planejamento: planejamento.md
  - Análise de requisitos:
    - Perfil do usuário: 
      - Questionário: 'requisitos/questionarios.md'
      - Perfil do Usuário: 'requisitos/perfil_do_usuário.md'
      - Personas: 'requisitos/personas.md'
    - Análise de tarefas: 
      - Análise Hierárquica de tarefas: 'requisitos/HTA.md'
      - Árvore de tarefas concorrentes: 'requisitos/CTT.md'
    - Princípios Gerais de Projeto: 'requisitos/principios.md'
    - Metas de Usabilidade: 'requisitos/usabilidade.md'
    - Guia de Estilo: 'requisitos/guiadeestilo.md'
  - Design, avaliação e desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: 'Design/nivel1/Tarefas/Planejamento.md'
        - Relato dos Resultados: 'Design/nivel1/Tarefas/Relato1.md'

      - Storyboard:
        - Storyboard:  'Design/nivel1/Storyboard/Storyboard.md'
        - Planejamento da Avaliação: 'Design/nivel1/Storyboard/Planejamento.md'
        - Relato dos Resultados : 'Design/nivel1/Storyboard/Relato1.md'

  - Atas de reunião:
    - Ata 01: 'Atas/Ata01.md'
    - Ata 02: 'Atas/Ata02.md'
    - Ata 03: 'Atas/Ata03.md'
    - Ata 04: 'Atas/Ata04.md'
  - Apresentaçōes:
    - Apresentação 1: 'Apresentacao/apresentacao1.md'
    - Apresentação 2: 'Apresentacao/apresentacao2.md'
    - Apresentação 3: 'Apresentacao/apresentacao3.md'
    - Apresentação 4: 'Apresentacao/apresentacao4.md'

